### ISSUE TITLE
Code Style / Linting

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#39] opened 2018-08-30 11:46 UTC
It may be worth using a linter such as `cpplint` to adhere to some code style rules, which can be factored in as a CI phase to enforce usage. 

`cpplint` seems sensible as it supports cuda and is readily installable via pip. It can also be configured to suppress rules we do not wish to adhere to if required.

**Comment by Robadob** [comment] 2019-11-02 20:17
Closing this, it's a duplicate of Issue #95

**Closed by Robadob** 2019-11-02 20:17 UTC
